const SCREENX = 640
const SCREENY = 480

const TILESIZE = 64

const NUMBER_OF_TILES_X = 10
const NUMBER_OF_TILES_Y = 7
const NUMBER_OF_LEVELS  = 1

SCROLLSPEED = 1/40

'Game Settings
SETTINGS_DIFFICULTY = 0.8 '0.6: easy 0.8: normal 1.0: expert 1.2:god
SETTINGS_VSYNC = 0
SETTINGS_FULLSCREEN = 0
SETTINGS_MUSIC_VOLUME = 30
KEY_USER_LEFT = K_LEFT
KEY_USER_RIGHT = K_RIGHT
KEY_USER_UP = K_UP
KEY_USER_DOWN = K_DOWN
KEY_USER_FIRE = K_SPACE



const GAME_STATE_GAME_IS_RUNNING = 0
const GAME_STATE_LEVEL_FINISHED = 1
const GAME_STATE_GAME_CANCELED = 2
const GAME_STATE_PLAYERS_DEAD = 3
const GAME_STATE_ALL_LEVEL_FINISHED = 4
GAME_STATE = GAME_STATE_GAME_IS_RUNNING

BACKGROUND_IMAGES_NUMBER = 0
BACKGROUND_IMAGES_SCROLLSPEED_INIT = 1/100
BACKGROUND_IMAGES_SCROLLSPEED = BACKGROUND_IMAGES_SCROLLSPEED_INIT
BACKGROUND_IMAGES_OFFSET = 0
BACKGROUND_IMAGES_POSITION_X = 0

ImageID_DynamicData_Offset = 0
ImageID = 0
ENEMY_IMAGE_ID_OFFSET = 0

SoundID_DynamicData_Offset = 0
SoundID = 0

const LAYER_BACK = 0
const LAYER_CENTER = 1
const LAYER_FRONT = 2

const CANVAS_MAIN = 0
const CANVAS_HEADER = 1
const CANVAS_MENUE = 2
CANVAS_SHAKE = false
const CANVAS_SHAKE_NUMBER_OF_ANIMATIONS = 4
CANVAS_SHAKE_ANIMATION_FRAME = 0
CANVAS_SHAKE_SPEED = 10
CANVAS_OFFSET = 0
DIM CANVAS_SHAKE_POS[4,2]
CANVAS_SHAKE_POS[0,0] = 2
CANVAS_SHAKE_POS[0,1] = -2
CANVAS_SHAKE_POS[1,0] = -2
CANVAS_SHAKE_POS[1,1] = -2
CANVAS_SHAKE_POS[2,0] = 2
CANVAS_SHAKE_POS[2,1] = 2
CANVAS_SHAKE_POS[3,0] = -2
CANVAS_SHAKE_POS[3,1] = 2

DIM COLOR_PALETTE[32]
COLOR_PALETTE[0] = rgb(36,38,114)
COLOR_PALETTE[1] = rgb(43,89,183)
COLOR_PALETTE[2] = rgb(53,174,235)
COLOR_PALETTE[3] = rgb(126,213,233)
COLOR_PALETTE[4] = rgb(244,233,233)
COLOR_PALETTE[5] = rgb(249,210,168)
COLOR_PALETTE[6] = rgb(249,184,124)
COLOR_PALETTE[7] = rgb(217,129,72)
COLOR_PALETTE[8] = rgb(141,105,112)
COLOR_PALETTE[9] = rgb(101,78,104)
COLOR_PALETTE[10] = rgb(25,13,20)
COLOR_PALETTE[11] = rgb(57,50,56)
COLOR_PALETTE[12] = rgb(97,99,107)
COLOR_PALETTE[13] = rgb(145,151,157)
COLOR_PALETTE[14] = rgb(196,208,216)
COLOR_PALETTE[15] = rgb(10,52,34)
COLOR_PALETTE[16] = rgb(32,102,36)
COLOR_PALETTE[17] = rgb(63,156,44)
COLOR_PALETTE[18] = rgb(181,206,45)
COLOR_PALETTE[19] = rgb(249,229,84)
COLOR_PALETTE[20] = rgb(253,193,26)
COLOR_PALETTE[21] = rgb(255,117,36)
COLOR_PALETTE[22] = rgb(233,54,43)
COLOR_PALETTE[23] = rgb(148,20,45)
COLOR_PALETTE[24] = rgb(84,14,53)
COLOR_PALETTE[25] = rgb(127,54,135)
COLOR_PALETTE[26] = rgb(189,85,150)
COLOR_PALETTE[27] = rgb(255,130,124)
COLOR_PALETTE[28] = rgb(249,170,139)
COLOR_PALETTE[29] = rgb(170,74,38)
COLOR_PALETTE[30] = rgb(116,27,11)
COLOR_PALETTE[31] = rgb(72,14,4)

HEADER_IMAGE_ID = 0
HEADER_ENERGYBAR_ID = 0

MENUE_IMAGE_ID_PLAY = 0
MENUE_IMAGE_ID_EXIT = 0
MENUE_IMAGE_ID_HIGHSCORE = 0
MENUE_IMAGE_ID_SETTINGS = 0
MENUE_IMAGE_ID_CREDITS = 0
MENUE_IMAGE_ID_ARROW = 0
MENUE_IMAGE_ID_FONT_64x64 = 0

const PLAYER_STATUS_NORMAL = 0
const PLAYER_STATUS_EXPLODING = 1
const PLAYER_STATUS_RESET = 2
const PLAYER_STATUS_DEAD = 3
const PLAYER_STATUS_SPAWNED = 4

const PLAYER_POSITION_X = 0
const PLAYER_POSITION_Y = 1
const PLAYER_ACCELERATION = 2
const PLAYER_MAX_ACCELERATION = 3
const PLAYER_ACCELERATION_X = 4
const PLAYER_ACCELERATION_Y = 5
const PLAYER_ANIMATION_FRAME = 6
const PLAYER_HITPOINTS = 7
const PLAYER_POINTS = 8
const PLAYER_LIVES = 9
const PLAYER_MAX_HITPOINTS = 10
const PLAYER_STATUS = 11
const PLAYER_SPAWN_TIMER = 12
const PLAYER_SHOT_TYPE = 13								'1+0+0  2: 2+0+0   3: 3+0+0   4: 3+1+0   5: 3+2+0   6: 3+3+0    7: 3+3+1   8: 3+3+2   9: 3+3+3 
const PLAYER_SHOT_DELAY = 14													

const PLAYER_SETTINGS_PLAYER_ANIMATION_SPEED = 100
const PLAYER_SETTINGS_NUMBER_OF_ANIMATIONS = 4
PLAYER_SETTINGS_TILES_OFFSET = 0
const PLAYER_SETTINGS_BOX_X1 = 12
const PLAYER_SETTINGS_BOX_Y1 = 26
const PLAYER_SETTINGS_BOX_X2 = 52
const PLAYER_SETTINGS_BOX_Y2 = 42
PLAYER_SETTINGS_EXPLOSION_TILE_OFFSET = 0
PLAYER_SETTINGS_WEAPON_1_P1_TILE_OFFSET = 0
PLAYER_SETTINGS_WEAPON_2_P1_TILE_OFFSET = 0
PLAYER_SETTINGS_SOUND_ENEMY_SHOT_HIT_OFFSET = 0
PLAYER_SETTINGS_SOUND_COLLISION_OFFSET = 0

'_______________ENEMY_________________________________________________________________________

NUMBER_OF_ENEMIES = 0
const MAX_NUMBER_OF_ENEMIES = 500
DIM EnemyList[MAX_NUMBER_OF_ENEMIES,41]

const ENEMY_STATUS_INACTIVE = 0
const ENEMY_STATUS_ACTIVE = 1
const ENEMY_STATUS_WAITING = 2
const ENEMY_STATUS_EXPLODING = 3
const ENEMY_STATUS_HIT = 4

ENEMY_SETTINGS_SOUND_OFFSET_EXPLODE_TYPE_1 = 0
ENEMY_SETTINGS_SOUND_OFFSET_EXPLODE_TYPE_2 = 0

'Path: f = A + B*(t-C)^D + F*sin(E*t)
const ENEMY_STATUS = 0
const ENEMY_TRIGGER_START_POSITION = 1
const ENEMY_TIME_START = 2
const ENEMY_PATH_X_A = 3
const ENEMY_PATH_X_B = 4
const ENEMY_PATH_X_C = 5
const ENEMY_PATH_X_D = 6
const ENEMY_PATH_X_E = 7
const ENEMY_PATH_X_F = 8
const ENEMY_PATH_X_STOP = 9
const ENEMY_PATH_Y_A = 10
const ENEMY_PATH_Y_B = 11
const ENEMY_PATH_Y_C = 12
const ENEMY_PATH_Y_D = 13
const ENEMY_PATH_Y_E = 14
const ENEMY_PATH_Y_F = 15
const ENEMY_PATH_Y_STOP = 16
const ENEMY_NUMBER_OF_ANIMATIONS = 17
const ENEMY_ANIMATION_FRAME = 18
const ENEMY_TILES_OFFSET = 19
const ENEMY_HITPOINTS = 20
const ENEMY_BOX_X1 = 21
const ENEMY_BOX_Y1 = 22
const ENEMY_BOX_X2 = 23
const ENEMY_BOX_Y2 = 24
const ENEMY_EXPLOSION_TILE_OFFSET = 25
const ENEMY_POINTS = 26
const ENEMY_SHOT_TRIGGER_START_POSITION = 27
const ENEMY_SHOT_NUMBER_OF_SHOTS = 28
const ENEMY_SHOT_DELAY = 29
const ENEMY_SHOT_ANGLE = 30
const ENEMY_SHOT_SPEED = 31
const ENEMY_SHOT_ANGLE_INCREASE = 32
const ENEMY_SHOT_TYPE_SETTING = 33
const ENEMY_SHOT_REMAINING_DELAY = 34
const ENEMY_BONUS_TYPE = 35
const ENEMY_SHOT_REPETITIONS = 36
const ENEMY_SHOT_REPETITIONS_DELAY = 37
const ENEMY_SHOT_NUMBER_OF_REMAINING_SHOTS = 38
const ENEMY_SHOT_REPETITIONS_REMAINING_DELAY = 39
const ENEMY_SHOT_CURRENT_ANGLE = 40

'________PLAYER_SHOTS_________________________________________________________________________________________

const MAX_PLAYER_SHOTS = 20
const PLAYER_SHOT_STATUS_INACTIVE = 0
const PLAYER_SHOT_STATUS_ACTIVE = 1
const PLAYER_SHOT_STATUS_EXPLOSION = 2

const PLAYER_SHOT_STATUS = 0
const PLAYER_SHOT_SHOT_TYPE = 1
const PLAYER_SHOT_POSITION_X = 2
const PLAYER_SHOT_POSITION_Y = 3
const PLAYER_SHOT_ANIMATION_FRAME = 4

const PLAYER_SHOTS_SETTINGS_SPEED = 0.5
const PLAYER_SHOTS_SETTINGS_DAMAGE_TYPE_1 = 100
const PLAYER_SHOTS_SETTINGS_DAMAGE_TYPE_2 = 200
const PLAYER_SHOTS_SETTINGS_DAMAGE_TYPE_3 = 300
PLAYER_SHOTS_SETTINGS_TILES_OFFSET_TYPE_1 = 1
PLAYER_SHOTS_SETTINGS_TILES_OFFSET_TYPE_2 = 1
PLAYER_SHOTS_SETTINGS_TILES_OFFSET_TYPE_3 = 1
const PLAYER_SHOTS_SETTINGS_DELAY = 400 'in ms
const PLAYER_SHOTS_SETTINGS_NUMBER_OF_ANIMATIONS = 4
const PLAYER_SHOTS_SETTINGS_ANIMATION_SPEED = 200
PLAYER_SHOTS_SETTINGS_NEXT_ID = 0
PLAYER_SHOTS_SETTINGS_DELAY_COUNTER = 0
const PLAYER_SHOTS_SETTINGS_TYPE_1_BOX_X1 = 22
const PLAYER_SHOTS_SETTINGS_TYPE_1_BOX_Y1 = 26
const PLAYER_SHOTS_SETTINGS_TYPE_1_BOX_X2 = 46
const PLAYER_SHOTS_SETTINGS_TYPE_1_BOX_Y2 = 36
const PLAYER_SHOTS_SETTINGS_TYPE_2_BOX_X1 = 20
const PLAYER_SHOTS_SETTINGS_TYPE_2_BOX_Y1 = 24
const PLAYER_SHOTS_SETTINGS_TYPE_2_BOX_X2 = 48
const PLAYER_SHOTS_SETTINGS_TYPE_2_BOX_Y2 = 38
const PLAYER_SHOTS_SETTINGS_TYPE_3_BOX_X1 = 18
const PLAYER_SHOTS_SETTINGS_TYPE_3_BOX_Y1 = 22
const PLAYER_SHOTS_SETTINGS_TYPE_3_BOX_X2 = 64 - 18
const PLAYER_SHOTS_SETTINGS_TYPE_3_BOX_Y2 = 64 - 22
PLAYER_SHOTS_SETTINGS_TILES_OFFSET_TYPE_1_EXPLODE = 0
PLAYER_SHOTS_SETTINGS_TILES_OFFSET_TYPE_2_EXPLODE = 0
PLAYER_SHOTS_SETTINGS_TILES_OFFSET_TYPE_3_EXPLODE = 0
const PLAYER_SHOTS_SETTINGS_EXPLODE_NUMBER_OF_ANIMATIONS = 4
const PLAYER_SHOTS_SETTINGS_EXPLODE_ANIMATIONS_SPEED = 50
PLAYER_SHOTS_SETTINGS_TYPE_1_SOUND_OFFSET = 0
PLAYER_SHOTS_SETTINGS_TYPE_2_SOUND_OFFSET = 0
PLAYER_SHOTS_SETTINGS_TYPE_3_SOUND_OFFSET = 0


'________ENEMY_SHOTS_________________________________________________________________________________________

ENEMY_SHOT_SETTINGS_TYPE_1_TILEOFFSET = 0
ENEMY_SHOT_SETTINGS_TYPE_1_BOX_X1 = 0
ENEMY_SHOT_SETTINGS_TYPE_1_BOX_Y1 = 0
ENEMY_SHOT_SETTINGS_TYPE_1_BOX_X2 = 9
ENEMY_SHOT_SETTINGS_TYPE_1_BOX_Y2 = 9
ENEMY_SHOT_SETTINGS_TYPE_1_NUMBER_OF_ANIMATIONS = 1
const ENEMY_SHOT_SETTINGS_TYPE_1_ANIMATION_SPEED = 100
ENEMY_SHOT_SETTINGS_TYPE_1_DAMAGE = 100
ENEMY_SHOT_SETTINGS_TYPE_1_TILES_OFFSET_EXPLODE = 0
ENEMY_SHOT_SETTINGS_TYPE_1_TILES_EXPLODE_SIZE_HALF = 32

ENEMY_SHOT_SETTINGS_TYPE_2_TILEOFFSET = 0
ENEMY_SHOT_SETTINGS_TYPE_2_BOX_X1 = 2
ENEMY_SHOT_SETTINGS_TYPE_2_BOX_Y1 = 2
ENEMY_SHOT_SETTINGS_TYPE_2_BOX_X2 = 22
ENEMY_SHOT_SETTINGS_TYPE_2_BOX_Y2 = 22
ENEMY_SHOT_SETTINGS_TYPE_2_NUMBER_OF_ANIMATIONS = 4
const ENEMY_SHOT_SETTINGS_TYPE_2_ANIMATION_SPEED = 100
ENEMY_SHOT_SETTINGS_TYPE_2_DAMAGE = 200
ENEMY_SHOT_SETTINGS_TYPE_2_TILES_OFFSET_EXPLODE = 0
ENEMY_SHOT_SETTINGS_TYPE_2_TILES_EXPLODE_SIZE_HALF = 12

ENEMY_SHOT_SETTINGS_TYPE_3_TILEOFFSET = 0
ENEMY_SHOT_SETTINGS_TYPE_3_BOX_X1 = 2
ENEMY_SHOT_SETTINGS_TYPE_3_BOX_Y1 = 2
ENEMY_SHOT_SETTINGS_TYPE_3_BOX_X2 = 12
ENEMY_SHOT_SETTINGS_TYPE_3_BOX_Y2 = 12
ENEMY_SHOT_SETTINGS_TYPE_3_NUMBER_OF_ANIMATIONS = 4
const ENEMY_SHOT_SETTINGS_TYPE_3_ANIMATION_SPEED = 100
ENEMY_SHOT_SETTINGS_TYPE_3_DAMAGE = 300
ENEMY_SHOT_SETTINGS_TYPE_3_TILES_OFFSET_EXPLODE = 0
ENEMY_SHOT_SETTINGS_TYPE_3_TILES_EXPLODE_SIZE_HALF = 0

const ENEMY_SHOT_SETTINGS_EXPLODE_NUMBER_OF_ANIMATIONS = 5
const ENEMY_SHOT_SETTINGS_EXPLODE_ANIMATIONS_SPEED = 50

ENEMY_SHOT_SETTINGS_SOUND_OFFSET = 0

const ENEMY_MAX_SHOTS = 80
ENEMY_SHOT_ID = 0
const ENEMY_SHOT_STATUS_INACTIVE = 0
const ENEMY_SHOT_STATUS_ACTIVE = 1
const ENEMY_SHOT_STATUS_EXPLOSION = 2

const ENEMY_SHOT_STATUS = 0
const ENEMY_SHOT_TYPE = 1	'3 different kind of shots
const ENEMY_SHOT_POSITION_X = 2
const ENEMY_SHOT_POSITION_Y = 3
const ENEMY_SHOT_ANIMATION_FRAME = 4
const ENEMY_SHOT_VX = 5
const ENEMY_SHOT_VY = 6

'________Bonus_________________________________________________________________________________________

BONUS_SETTINGS_TILEOFFSET_HEALTH = 0
BONUS_SETTINGS_TILEOFFSET_SPEED = 0
BONUS_SETTINGS_TILEOFFSET_POINTS = 0
BONUS_SETTINGS_TILEOFFSET_POWER = 0
BONUS_SETTINGS_TILEOFFSET_LIFE = 0
BONUS_SETTINGS_TILEOFFSET_SHOT_REPETITION = 0
const BONUS_SETTINGS_BOX_X1 = 20
const BONUS_SETTINGS_BOX_Y1 = 20
const BONUS_SETTINGS_BOX_X2 = 42
const BONUS_SETTINGS_BOX_Y2 = 42
const BONUS_SETTINGS_NUMBER_OF_ANIMATIONS = 7
const BONUS_SETTINGS_ANIMATION_SPEED = 50
BONUS_SETTINGS_SOUND_OFFSET = 0

const BONUS_TYPE_NONE = 0
const BONUS_TYPE_HEALTH = 1
const BONUS_TYPE_SPEED  = 2
const BONUS_TYPE_POINTS = 3
const BONUS_TYPE_POWER  = 4
const BONUS_TYPE_LIFE   = 5
const BONUS_TYPE_SHOT_REPETITION = 6

const BONUS_MAX_BONUS = 10
BONUS_ID = 0
const BONUS_STATUS_INACTIVE = 0
const BONUS_STATUS_ACTIVE = 1

const BONUS_STATUS = 0
const BONUS_TYPE = 1
const BONUS_POSITION_X = 2
const BONUS_POSITION_Y = 3
const BONUS_ANIMATION_FRAME = 4
const BONUS_POINTS = 5


'________LOAD LEVEL DATA____________________________________________________________________________________
const MAX_LEVEL_SIZE_X = 1000
const MAX_LEVEL_SIZE_Y = 7
LEVEL_SIZE_X = 0
LEVEL_SIZE_Y = 0




