JOYSTICK_NUMBER = 0			' Which joystick to querry?
JOYSTICK_DEVICE = 1 		' Which part of the joystick: Button, Axis or Hat?
JOYSTICK_DEVICE_NUMBER = 2	' What is the number of that device: i.e. button number 2, or Axis 1
JOYSTICK_DEVICE_VALUE = 3	' Just for hat: What is the direction of the hat: i.e.: HAT_LEFT 

JOYSTICK_BUTTON = 0
JOYSTICK_HAT = 1
JOYSTICK_AXIS = 2

'Define Joystick buttons
JOYSTICK_LEFT = 0
JOYSTICK_RIGHT = 1
JOYSTICK_UP = 2
JOYSTICK_DOWN = 3
JOYSTICK_FIRE = 4
JOYSTICK_ESCAPE = 5

DIM JOYSTICK[6,4]
DIM JOYSTICK_TEMP[4]

'Success = SetJoyButton(JOYSTICK_LEFT)
function SetJoystickButton()

	for joy_num = 0 to NumJoysticks() - 1

		if NumJoyHats(joy_num) > 0 then
			
			for ii = 0 to NumJoyHats(joy_num)-1
	
				Select Case JoyHat(joy_num, ii)
					Case HAT_LEFT
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_LEFT
						return True
					Case HAT_RIGHT
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_RIGHT
						return True
					Case HAT_UP
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_UP
						return True
					Case HAT_DOWN
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_DOWN
						return True
					Case HAT_LEFTUP
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_LEFTUP
						return True
					Case HAT_LEFTDOWN
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_LEFTDOWN
						return True
					Case HAT_RIGHTUP
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_RIGHTUP
						return True
					Case HAT_RIGHTDOWN
						JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
						JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_HAT
						JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii 
						JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = HAT_RIGHTDOWN
						return True
					'Case HAT_CENTERED
						'JOYSTICK[JButton, JOYSTICK_NUMBER] = joy_num
						'JOYSTICK[JButton, JOYSTICK_DEVICE] = JOYSTICK_HAT
						'JOYSTICK[JButton, JOYSTICK_DEVICE_NUMBER] = HAT_CENTERED
						'return True
				End Select
			next
		
		End If
		
		If NumJoyButtons(joy_num) > 0 then
			for ii = 0 to NumJoyButtons(joy_num) - 1
				if(joybutton(joy_num, ii)) then
					JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
					JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_BUTTON
					JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii
					JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = 0
					return True
				end if
			next
		End If
		
		If NumJoyAxes(joy_num) > 0 then
			for ii = 0 to NumJoyAxes(joy_num) - 1
				if(JoyAxis(joy_num, ii) > 500 or JoyAxis(joy_num, ii) < -500) then
					JOYSTICK_TEMP[JOYSTICK_NUMBER] = joy_num
					JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK_AXIS
					JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = ii
					JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = 0
					return True
				end if
			next
		End If
	
	next
	
	return False
	
end function


' Value = GetJoystick(JOYSTICK_LEFT)
' Value ist true of false for Button and Hat, and a number between 200 and 2^15 for axis if axis is used; otherwise false
function GetJoystick(JButton)
		
	select case JOYSTICK[JButton, JOYSTICK_DEVICE]
		case JOYSTICK_HAT
			if(JoyHat(JOYSTICK[JButton, JOYSTICK_NUMBER], JOYSTICK[JButton, JOYSTICK_DEVICE_NUMBER]) = JOYSTICK[JButton, JOYSTICK_DEVICE_VALUE]) then
				return True
			else
				return false
			end if
		case JOYSTICK_BUTTON
			if(JoyButton(JOYSTICK[JButton, JOYSTICK_NUMBER], JOYSTICK[JButton, JOYSTICK_DEVICE_NUMBER])) then
				return True
			else
				return false
			end if
		case JOYSTICK_AXIS
			if(JoyAxis(JOYSTICK[JButton, JOYSTICK_NUMBER], JOYSTICK[JButton, JOYSTICK_DEVICE_NUMBER]) * JOYSTICK[JButton, JOYSTICK_DEVICE_VALUE] > 500) then
					return JoyAxis(JOYSTICK[JButton, JOYSTICK_NUMBER], JOYSTICK[JButton, JOYSTICK_DEVICE_NUMBER]) * JOYSTICK[JButton, JOYSTICK_DEVICE_VALUE]
			else
				return false
			end if
	end select
	
	
end function

sub InitJoystick()

		JOYSTICK[JOYSTICK_LEFT, JOYSTICK_NUMBER] = 0
		JOYSTICK[JOYSTICK_LEFT, JOYSTICK_DEVICE] = JOYSTICK_AXIS
		JOYSTICK[JOYSTICK_LEFT, JOYSTICK_DEVICE_NUMBER] = 0
		JOYSTICK[JOYSTICK_LEFT, JOYSTICK_DEVICE_VALUE] = -1
		
		JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_NUMBER] = 0
		JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_DEVICE] = JOYSTICK_AXIS
		JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_DEVICE_NUMBER] = 0
		JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_DEVICE_VALUE] = 1
		
		JOYSTICK[JOYSTICK_UP, JOYSTICK_NUMBER] = 0
		JOYSTICK[JOYSTICK_UP, JOYSTICK_DEVICE] = JOYSTICK_AXIS
		JOYSTICK[JOYSTICK_UP, JOYSTICK_DEVICE_NUMBER] = 1
		JOYSTICK[JOYSTICK_UP, JOYSTICK_DEVICE_VALUE] = -1
		
		JOYSTICK[JOYSTICK_DOWN, JOYSTICK_NUMBER] = 0
		JOYSTICK[JOYSTICK_DOWN, JOYSTICK_DEVICE] = JOYSTICK_AXIS
		JOYSTICK[JOYSTICK_DOWN, JOYSTICK_DEVICE_NUMBER] = 1
		JOYSTICK[JOYSTICK_DOWN, JOYSTICK_DEVICE_VALUE] = 1
		
		JOYSTICK[JOYSTICK_FIRE, JOYSTICK_NUMBER] = 0
		JOYSTICK[JOYSTICK_FIRE, JOYSTICK_DEVICE] = JOYSTICK_BUTTON
		JOYSTICK[JOYSTICK_FIRE, JOYSTICK_DEVICE_NUMBER] = 0
		JOYSTICK[JOYSTICK_FIRE, JOYSTICK_DEVICE_VALUE] = 0
		
		JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_NUMBER] = 0
		JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_DEVICE] = JOYSTICK_BUTTON
		JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_DEVICE_NUMBER] = 2
		JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_DEVICE_VALUE] = 0
		
		

end sub

'Returns true, if J is already set for one of the other directions
function CompareJoystickSetting(J)

	if(J <> JOYSTICK_LEFT) then
		if(JOYSTICK_TEMP[JOYSTICK_NUMBER] = JOYSTICK[JOYSTICK_LEFT, JOYSTICK_NUMBER]) then
			if(JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK[JOYSTICK_LEFT,JOYSTICK_DEVICE]) then 
				if(JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = JOYSTICK[JOYSTICK_LEFT, JOYSTICK_DEVICE_NUMBER]) then 
					if(JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = JOYSTICK[JOYSTICK_LEFT, JOYSTICK_DEVICE_VALUE]) then
						return false
					end if
				end if
			end if
		end if
	end if
	
	if(J <> JOYSTICK_RIGHT) then
		if(JOYSTICK_TEMP[JOYSTICK_NUMBER] = JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_NUMBER]) then
			if(JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK[JOYSTICK_RIGHT,JOYSTICK_DEVICE]) then 
				if(JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_DEVICE_NUMBER]) then 
					if(JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = JOYSTICK[JOYSTICK_RIGHT, JOYSTICK_DEVICE_VALUE]) then
						return false
					end if
				end if
			end if
		end if
	end if
	
	if(J <> JOYSTICK_UP) then
		if(JOYSTICK_TEMP[JOYSTICK_NUMBER] = JOYSTICK[JOYSTICK_UP, JOYSTICK_NUMBER]) then
			if(JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK[JOYSTICK_UP,JOYSTICK_DEVICE]) then 
				if(JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = JOYSTICK[JOYSTICK_UP, JOYSTICK_DEVICE_NUMBER]) then 
					if(JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = JOYSTICK[JOYSTICK_UP, JOYSTICK_DEVICE_VALUE]) then
						return false
					end if
				end if
			end if
		end if
	end if
	
	if(J <> JOYSTICK_DOWN) then
		if(JOYSTICK_TEMP[JOYSTICK_NUMBER] = JOYSTICK[JOYSTICK_DOWN, JOYSTICK_NUMBER]) then
			if(JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK[JOYSTICK_DOWN,JOYSTICK_DEVICE]) then 
				if(JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = JOYSTICK[JOYSTICK_DOWN, JOYSTICK_DEVICE_NUMBER]) then 
					if(JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = JOYSTICK[JOYSTICK_DOWN, JOYSTICK_DEVICE_VALUE]) then
						return false
					end if
				end if
			end if
		end if
	end if

	if(J <> JOYSTICK_ESCAPE) then
		if(JOYSTICK_TEMP[JOYSTICK_NUMBER] = JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_NUMBER]) then
			if(JOYSTICK_TEMP[JOYSTICK_DEVICE] = JOYSTICK[JOYSTICK_ESCAPE,JOYSTICK_DEVICE]) then 
				if(JOYSTICK_TEMP[JOYSTICK_DEVICE_NUMBER] = JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_DEVICE_NUMBER]) then 
					if(JOYSTICK_TEMP[JOYSTICK_DEVICE_VALUE] = JOYSTICK[JOYSTICK_ESCAPE, JOYSTICK_DEVICE_VALUE]) then
						return false
					end if
				end if
			end if
		end if
	end if

	return true

end function
