sub ProcessInput()
	if(key(K_ESCAPE) OR GetJoystick(JOYSTICK_ESCAPE)) then
		GAME_STATE = GAME_STATE_GAME_CANCELED
	end if


	if(key(K_LEFT) OR key(KEY_USER_LEFT) OR GetJoystick(JOYSTICK_LEFT)) then
		if(Player[0, PLAYER_POSITION_X] > 0) then
			Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_ACCELERATION_X] - TimeStep * Player[0, PLAYER_ACCELERATION]
		else
			Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_ACCELERATION_X] - TimeStep * Player[0, PLAYER_ACCELERATION] * 0.15
		end if
  		if(Player[0, PLAYER_ACCELERATION_X] < -1*Player[0, PLAYER_MAX_ACCELERATION]) Then
			Player[0, PLAYER_ACCELERATION_X] = -1*Player[0, PLAYER_MAX_ACCELERATION]
		end if
	end if
	if(key(K_RIGHT) OR key(KEY_USER_RIGHT) OR GetJoystick(JOYSTICK_RIGHT)) then
		if(Player[0, PLAYER_POSITION_X] < SCREENX - TILESIZE) then
			Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_ACCELERATION_X] + TimeStep * Player[0, PLAYER_ACCELERATION]
		else
			Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_ACCELERATION_X] + TimeStep * Player[0, PLAYER_ACCELERATION] * 0.15
		end if		
		if(Player[0, PLAYER_ACCELERATION_X] > Player[0, PLAYER_MAX_ACCELERATION]) Then
			Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_MAX_ACCELERATION]
		end if
	end if
    if(key(K_UP) OR key(KEY_USER_UP) OR GetJoystick(JOYSTICK_UP)) then
		if(Player[0, PLAYER_POSITION_Y] > 0) then
			Player[0, PLAYER_ACCELERATION_Y] = Player[0, PLAYER_ACCELERATION_Y] - TimeStep * Player[0, PLAYER_ACCELERATION]
		end if
		if(Player[0, PLAYER_ACCELERATION_Y] < -1*Player[0, PLAYER_MAX_ACCELERATION]) Then
			Player[0, PLAYER_ACCELERATION_Y] = -1*Player[0, PLAYER_MAX_ACCELERATION]
		end if
	end if
	if(key(K_DOWN) OR key(KEY_USER_DOWN) OR GetJoystick(JOYSTICK_DOWN)) then
		if(Player[0, PLAYER_POSITION_Y] < SCREENY) then
    		Player[0, PLAYER_ACCELERATION_Y] = Player[0, PLAYER_ACCELERATION_Y] + TimeStep * Player[0, PLAYER_ACCELERATION]
		end if
		if(Player[0, PLAYER_ACCELERATION_Y] > Player[0, PLAYER_MAX_ACCELERATION]) Then
			Player[0, PLAYER_ACCELERATION_Y] = Player[0, PLAYER_MAX_ACCELERATION]
		end if
	end if
	
	if(Player[0, PLAYER_ACCELERATION_X] > 0) Then
		Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_ACCELERATION_X] - TimeStep * Player[0, PLAYER_ACCELERATION] * 0.2
		if(Player[0, PLAYER_ACCELERATION_X] < 0) Then
			Player[0, PLAYER_ACCELERATION_X] = 0
		end if
	else
		Player[0, PLAYER_ACCELERATION_X] = Player[0, PLAYER_ACCELERATION_X] + TimeStep * Player[0, PLAYER_ACCELERATION] * 0.2
		if(Player[0, PLAYER_ACCELERATION_X] > 0) Then
			Player[0, PLAYER_ACCELERATION_X] = 0
		end if
	end if
  
	if(Player[0, PLAYER_ACCELERATION_Y] > 0) Then
		Player[0, PLAYER_ACCELERATION_Y] = Player[0, PLAYER_ACCELERATION_Y] - TimeStep * Player[0, PLAYER_ACCELERATION] * 0.2
		if(Player[0, PLAYER_ACCELERATION_Y] < 0) Then
			Player[0, PLAYER_ACCELERATION_Y] = 0
		end if
	else
		Player[0, PLAYER_ACCELERATION_Y] = Player[0, PLAYER_ACCELERATION_Y] + TimeStep * Player[0, PLAYER_ACCELERATION] * 0.2
		if(Player[0, PLAYER_ACCELERATION_Y] > 0) Then
			Player[0, PLAYER_ACCELERATION_Y] = 0
		end if
	end if
	
	if(key(K_SPACE) OR key(KEY_USER_FIRE) OR GetJoystick(JOYSTICK_FIRE)) Then
	
		if(PLAYER_SHOTS_SETTINGS_DELAY_COUNTER > Player[0, PLAYER_SHOT_DELAY]) then
					
			
			'Add central shot
		     
			PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_STATUS] = 1
			select case Player[0, PLAYER_SHOT_TYPE]
				case 1
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 1
					'PlaySound(PLAYER_SHOTS_SETTINGS_TYPE_1_SOUND_OFFSET, SOUND_CHANNEL_PLAYER_SHOT,0)		
					Sound(PLAYER_SHOTS_SETTINGS_TYPE_1_SOUND_OFFSET)		
				case 2
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 2
					'PlaySound(PLAYER_SHOTS_SETTINGS_TYPE_2_SOUND_OFFSET, SOUND_CHANNEL_PLAYER_SHOT,0)		
					Sound(PLAYER_SHOTS_SETTINGS_TYPE_2_SOUND_OFFSET)
				default
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 3
					'PlaySound(PLAYER_SHOTS_SETTINGS_TYPE_3_SOUND_OFFSET, SOUND_CHANNEL_PLAYER_SHOT,0)		
					Sound(PLAYER_SHOTS_SETTINGS_TYPE_3_SOUND_OFFSET)
			end select
			
			PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_POSITION_X] = Player[0, PLAYER_POSITION_X] + 28
			PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_POSITION_Y] = Player[0, PLAYER_POSITION_Y]
			PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_ANIMATION_FRAME] = 0
			
			PLAYER_SHOTS_SETTINGS_NEXT_ID = PLAYER_SHOTS_SETTINGS_NEXT_ID + 1
			if(PLAYER_SHOTS_SETTINGS_NEXT_ID = MAX_PLAYER_SHOTS) Then
				PLAYER_SHOTS_SETTINGS_NEXT_ID = 0
			end if
			
			'Add top shot
			
			if(Player[0, PLAYER_SHOT_TYPE] > 3) then
				PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_STATUS] = 1
				select case Player[0, PLAYER_SHOT_TYPE]
					case 4
						PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 1
					case 5
						PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 2	
					default
						PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 3
				end select
				PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_POSITION_X] = Player[0, PLAYER_POSITION_X] - 4
				PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_POSITION_Y] = Player[0, PLAYER_POSITION_Y] - 26
				PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_ANIMATION_FRAME] = 0
				
				PLAYER_SHOTS_SETTINGS_NEXT_ID = PLAYER_SHOTS_SETTINGS_NEXT_ID + 1
				if(PLAYER_SHOTS_SETTINGS_NEXT_ID = MAX_PLAYER_SHOTS) Then
					PLAYER_SHOTS_SETTINGS_NEXT_ID = 0
				end if
			end if
			if(Player[0, PLAYER_SHOT_TYPE] > 6) then
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_STATUS] = 1
					select case Player[0, PLAYER_SHOT_TYPE]
						case 7
							PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 1
						case 8
							PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 2	
						case 9
							PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_SHOT_TYPE] = 3
					end select
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_POSITION_X] = Player[0, PLAYER_POSITION_X] - 4
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_POSITION_Y] = Player[0, PLAYER_POSITION_Y] + 26
					PlayerShots[PLAYER_SHOTS_SETTINGS_NEXT_ID, PLAYER_SHOT_ANIMATION_FRAME] = 0
					
					PLAYER_SHOTS_SETTINGS_NEXT_ID = PLAYER_SHOTS_SETTINGS_NEXT_ID + 1
					if(PLAYER_SHOTS_SETTINGS_NEXT_ID = MAX_PLAYER_SHOTS) Then
						PLAYER_SHOTS_SETTINGS_NEXT_ID = 0
					end if
			end if
			
			PLAYER_SHOTS_SETTINGS_DELAY_COUNTER = 0
			
		end if
	end if
end sub
